### ISSUE TITLE
Incompatible Firmware

### ISSUE THREAD

**Issue by sammichael25** [hoiberg/eaze#4]
I am using inav 1.7.4 and i get api version is too old or too new

**Comment by hoiberg** [comment]
Looking at the iNav repository, the API version has been upped to 2.0 on august 27, and since Eaze has been made for API versions 1.x, it means it is no longer compatible with iNav.

From msp_protocol.h:

```
 * Consumers of the API (API clients) SHOULD first attempt to get a response from the MSP_API_VERSION command.
[...]
 * API clients should NOT attempt any communication if they can't handle the returned API MAJOR VERSION.
```

So Eaze would have to be updated to be compatible with the newest versions of iNav, something I cannot do at the moment (plus I'm unfamiliar with iNav).
